[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_PATHS = "dist/*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200